In [1]:
import pandas as pd

In [5]:
subscriptions = pd.read_csv('./subscriptions.csv')

In [7]:
monthly_revenue = pd.read_csv('./monthly_revenue.csv')

In [11]:
subscriptions.head()

,customer_id,plan,billing_cycle,industry,company_size,seats,monthly_revenue,acquisition_channel,region,signup_date,churned,churn_date,churn_reason,support_tickets_12mo,nps_score,feature_usage_pct,upgraded
0,CUST-0001,Professional,Monthly,Retail,51-200,64,825.55,Organic Search,North America,2022-06-27,Yes,2024-03-05,Price Too High,13,3,15,No
1,CUST-0002,Professional,Annual,Retail,51-200,35,409.62,Direct Sales,North America,2023-03-19,No,NaN,NaN,1,3,52,Yes
2,CUST-0003,Starter,Annual,Finance,500+,266,1004.49,Partner,North America,2024-10-19,Yes,2025-04-13,Price Too High,10,4,31,No
3,CUST-0004,Business,Annual,Real Estate,11-50,34,1006.44,Partner,Europe,2023-01-07,No,NaN,NaN,3,7,58,No
4,CUST-0005,Starter,Annual,Manufacturing,51-200,48,198.43,Direct Sales,North America,2025-09-23,No,NaN,NaN,3,7,59,No

In [21]:
subscriptions.info()

<class 'pandas.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   customer_id           600 non-null    str
 1   plan                  600 non-null    str
 2   billing_cycle         600 non-null    str
 3   industry              600 non-null    str
 4   company_size          600 non-null    str
 5   seats                 600 non-null    int64
 6   monthly_revenue       600 non-null    float64
 7   acquisition_channel   600 non-null    str
 8   region                600 non-null    str
 9   signup_date           600 non-null    str
 10  churned               600 non-null    str
 11  churn_date            313 non-null    str
 12  churn_reason          313 non-null    str
 13  support_tickets_12mo  600 non-null    int64
 14  nps_score             600 non-null    int64
 15  feature_usage_pct     600 non-null    int64
 16  upgraded              600 non-null    str
dtypes: float64(1), int64(4), str(12)
memory usage: 130.8 KB

In [23]:
monthly_revenue.head()

,month,total_active_customers,new_customers,churned_customers,monthly_churn_rate_pct,total_mrr,avg_revenue_per_customer,customer_acquisition_cost
0,2022-01,0,5,0,0.00,0.00,0.00,164.92
1,2022-02,5,10,1,20.00,7333.07,1466.61,189.21
2,2022-03,14,13,0,0.00,12301.16,878.65,139.49
3,2022-04,28,11,3,10.71,24798.76,885.67,259.09
4,2022-05,35,11,1,2.86,29091.88,831.20,152.96

In [37]:
monthly_revenue.info()

<class 'pandas.DataFrame'>
RangeIndex: 48 entries, 0 to 47
Data columns (total 8 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   month                      48 non-null     str
 1   total_active_customers     48 non-null     int64
 2   new_customers              48 non-null     int64
 3   churned_customers          48 non-null     int64
 4   monthly_churn_rate_pct     48 non-null     float64
 5   total_mrr                  48 non-null     float64
 6   avg_revenue_per_customer   48 non-null     float64
 7   customer_acquisition_cost  48 non-null     float64
dtypes: float64(4), int64(3), str(1)
memory usage: 3.5 KB

In [38]:
monthly_revenue['month_dt'] = pd.to_datetime(monthly_revenue['month'])

In [39]:
monthly_revenue.head()

,month,total_active_customers,new_customers,churned_customers,monthly_churn_rate_pct,total_mrr,avg_revenue_per_customer,customer_acquisition_cost,month_dt
0,2022-01,0,5,0,0.00,0.00,0.00,164.92,2022-01-01
1,2022-02,5,10,1,20.00,7333.07,1466.61,189.21,2022-02-01
2,2022-03,14,13,0,0.00,12301.16,878.65,139.49,2022-03-01
3,2022-04,28,11,3,10.71,24798.76,885.67,259.09,2022-04-01
4,2022-05,35,11,1,2.86,29091.88,831.20,152.96,2022-05-01

In [ ]:
subscriptions.head()

,customer_id,plan,billing_cycle,industry,company_size,seats,monthly_revenue,acquisition_channel,region,signup_date,churned,churn_date,churn_reason,support_tickets_12mo,nps_score,feature_usage_pct,upgraded
0,CUST-0001,Professional,Monthly,Retail,51-200,64,825.55,Organic Search,North America,2022-06-27,Yes,2024-03-05,Price Too High,13,3,15,No
1,CUST-0002,Professional,Annual,Retail,51-200,35,409.62,Direct Sales,North America,2023-03-19,No,NaN,NaN,1,3,52,Yes
2,CUST-0003,Starter,Annual,Finance,500+,266,1004.49,Partner,North America,2024-10-19,Yes,2025-04-13,Price Too High,10,4,31,No
3,CUST-0004,Business,Annual,Real Estate,11-50,34,1006.44,Partner,Europe,2023-01-07,No,NaN,NaN,3,7,58,No
4,CUST-0005,Starter,Annual,Manufacturing,51-200,48,198.43,Direct Sales,North America,2025-09-23,No,NaN,NaN,3,7,59,No

In [30]:
subscriptions['signup_date_dt'] = pd.to_datetime(subscriptions['signup_date'])

In [31]:
subscriptions['churn_date_dt'] = pd.to_datetime(subscriptions['churn_date'])

In [32]:
subscriptions.info()

<class 'pandas.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   customer_id           600 non-null    str
 1   plan                  600 non-null    str
 2   billing_cycle         600 non-null    str
 3   industry              600 non-null    str
 4   company_size          600 non-null    str
 5   seats                 600 non-null    int64
 6   monthly_revenue       600 non-null    float64
 7   acquisition_channel   600 non-null    str
 8   region                600 non-null    str
 9   signup_date           600 non-null    datetime64[us]
 10  churned               600 non-null    str
 11  churn_date            313 non-null    datetime64[us]
 12  churn_reason          313 non-null    str
 13  support_tickets_12mo  600 non-null    int64
 14  nps_score             600 non-null    int64
 15  feature_usage_pct     600 non-null    int64
 16  upgraded              600 non-null    str
 17  signup_date_dt        600 non-null    datetime64[us]
 18  churn_date_dt         313 non-null    datetime64[us]
dtypes: datetime64[us](4), float64(1), int64(4), str(10)
memory usage: 131.2 KB

In [34]:
subscriptions.head()

,customer_id,plan,billing_cycle,industry,company_size,seats,monthly_revenue,acquisition_channel,region,signup_date,churned,churn_date,churn_reason,support_tickets_12mo,nps_score,feature_usage_pct,upgraded,signup_date_dt,churn_date_dt
0,CUST-0001,Professional,Monthly,Retail,51-200,64,825.55,Organic Search,North America,2022-06-27,Yes,2024-03-05,Price Too High,13,3,15,No,2022-06-27,2024-03-05
1,CUST-0002,Professional,Annual,Retail,51-200,35,409.62,Direct Sales,North America,2023-03-19,No,NaT,NaN,1,3,52,Yes,2023-03-19,NaT
2,CUST-0003,Starter,Annual,Finance,500+,266,1004.49,Partner,North America,2024-10-19,Yes,2025-04-13,Price Too High,10,4,31,No,2024-10-19,2025-04-13
3,CUST-0004,Business,Annual,Real Estate,11-50,34,1006.44,Partner,Europe,2023-01-07,No,NaT,NaN,3,7,58,No,2023-01-07,NaT
4,CUST-0005,Starter,Annual,Manufacturing,51-200,48,198.43,Direct Sales,North America,2025-09-23,No,NaT,NaN,3,7,59,No,2025-09-23,NaT

In [ ]:
## Let's see all the reasons there are churn is happennning ##
subscriptions['churn_reason'].unique()

<ArrowStringArray>
[     'Price Too High',                   nan,        'Poor Support',
 'Switched Competitor',         'Budget Cuts',      'Company Closed',
    'No Longer Needed',    'Missing Features']
Length: 8, dtype: str

In [40]:
subscriptions.describe()

,seats,monthly_revenue,signup_date,churn_date,support_tickets_12mo,nps_score,feature_usage_pct,signup_date_dt,churn_date_dt
count,600.000000,600.000000,600,313,600.000000,600.000000,600.000000,600,313
mean,42.450000,817.654300,2024-01-16 17:48:00,2024-06-04 07:35:27.795527,6.480000,4.365000,40.638333,2024-01-16 17:48:00,2024-06-04 07:35:27.795527
min,1.000000,24.650000,2022-01-06 00:00:00,2022-02-14 00:00:00,0.000000,1.000000,10.000000,2022-01-06 00:00:00,2022-02-14 00:00:00
25%,7.000000,137.137500,2023-01-17 00:00:00,2023-08-24 00:00:00,3.000000,2.000000,22.750000,2023-01-17 00:00:00,2023-08-24 00:00:00
50%,26.000000,348.250000,2024-01-18 12:00:00,2024-07-20 00:00:00,6.000000,4.000000,36.000000,2024-01-18 12:00:00,2024-07-20 00:00:00
75%,58.000000,874.832500,2025-01-04 12:00:00,2025-04-23 00:00:00,10.000000,6.000000,50.000000,2025-01-04 12:00:00,2025-04-23 00:00:00
max,297.000000,10978.000000,2025-12-31 00:00:00,2025-12-19 00:00:00,15.000000,10.000000,95.000000,2025-12-31 00:00:00,2025-12-19 00:00:00
std,51.279823,1352.584783,NaN,NaN,4.271613,2.650185,22.749801,NaN,NaN

In [41]:
monthly_revenue.describe()

,total_active_customers,new_customers,churned_customers,monthly_churn_rate_pct,total_mrr,avg_revenue_per_customer,customer_acquisition_cost,month_dt
count,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48
mean,167.416667,12.500000,6.520833,4.518958,174888.413958,1010.218958,200.040625,2023-12-16 11:00:00
min,0.000000,5.000000,0.000000,0.000000,0.000000,0.000000,122.990000,2022-01-01 00:00:00
25%,104.000000,10.750000,4.000000,3.007500,102605.177500,1009.865000,150.267500,2022-12-24 06:00:00
50%,184.500000,13.000000,7.000000,3.755000,190681.445000,1030.135000,197.250000,2023-12-16 12:00:00
75%,241.750000,14.250000,8.250000,4.552500,262177.912500,1072.027500,249.187500,2024-12-08 18:00:00
max,281.000000,19.000000,17.000000,20.000000,292628.610000,1466.610000,279.590000,2025-12-01 00:00:00
std,85.274234,3.339002,3.414547,3.251457,92619.227429,175.723630,52.694255,NaN

In [46]:
subscriptions[subscriptions['churned']== 'Yes'].head()

,customer_id,plan,billing_cycle,industry,company_size,seats,monthly_revenue,acquisition_channel,region,signup_date,churned,churn_date,churn_reason,support_tickets_12mo,nps_score,feature_usage_pct,upgraded,signup_date_dt,churn_date_dt
0,CUST-0001,Professional,Monthly,Retail,51-200,64,825.55,Organic Search,North America,2022-06-27,Yes,2024-03-05,Price Too High,13,3,15,No,2022-06-27,2024-03-05
2,CUST-0003,Starter,Annual,Finance,500+,266,1004.49,Partner,North America,2024-10-19,Yes,2025-04-13,Price Too High,10,4,31,No,2024-10-19,2025-04-13
6,CUST-0007,Starter,Monthly,Finance,201-500,121,551.00,Partner,Europe,2024-03-07,Yes,2025-04-08,Poor Support,0,2,14,No,2024-03-07,2025-04-08
7,CUST-0008,Starter,Monthly,Technology,51-200,48,233.45,Referral,Europe,2025-04-08,Yes,2025-06-08,Price Too High,10,2,28,No,2025-04-08,2025-06-08
8,CUST-0009,Starter,Monthly,Media,1-10,3,37.70,Partner,North America,2023-01-22,Yes,2023-04-21,Switched Competitor,5,6,15,No,2023-01-22,2023-04-21

In [54]:
## churn rate by plan ##
churn_by_plan = subscriptions[subscriptions['churned'] == 'Yes']

In [55]:
churn_by_plan.head()

,customer_id,plan,billing_cycle,industry,company_size,seats,monthly_revenue,acquisition_channel,region,signup_date,churned,churn_date,churn_reason,support_tickets_12mo,nps_score,feature_usage_pct,upgraded,signup_date_dt,churn_date_dt
0,CUST-0001,Professional,Monthly,Retail,51-200,64,825.55,Organic Search,North America,2022-06-27,Yes,2024-03-05,Price Too High,13,3,15,No,2022-06-27,2024-03-05
2,CUST-0003,Starter,Annual,Finance,500+,266,1004.49,Partner,North America,2024-10-19,Yes,2025-04-13,Price Too High,10,4,31,No,2024-10-19,2025-04-13
6,CUST-0007,Starter,Monthly,Finance,201-500,121,551.00,Partner,Europe,2024-03-07,Yes,2025-04-08,Poor Support,0,2,14,No,2024-03-07,2025-04-08
7,CUST-0008,Starter,Monthly,Technology,51-200,48,233.45,Referral,Europe,2025-04-08,Yes,2025-06-08,Price Too High,10,2,28,No,2025-04-08,2025-06-08
8,CUST-0009,Starter,Monthly,Media,1-10,3,37.70,Partner,North America,2023-01-22,Yes,2023-04-21,Switched Competitor,5,6,15,No,2023-01-22,2023-04-21

In [76]:
data_columns = ['plan', 'industry', 'acquisition_channel', 'region', 'churn_reason', 'company_size']

In [77]:
## calculating churns by different categories and reasons ## 
for col in data_columns: 
    print(f"\n{col}:")
    print(churn_by_plan[col].value_counts())

plan:
plan
Starter         153
Professional     83
Business         66
Enterprise       11
Name: count, dtype: int64

industry:
industry
Real Estate      37
Finance          36
Healthcare       35
Education        34
Consulting       32
Manufacturing    31
Legal            31
Retail           30
Media            24
Technology       23
Name: count, dtype: int64

acquisition_channel:
acquisition_channel
Referral          76
Organic Search    67
Paid Ads          61
Partner           58
Social Media      29
Direct Sales      22
Name: count, dtype: int64

region:
region
North America    139
Europe            89
Asia Pacific      48
Latin America     37
Name: count, dtype: int64

churn_reason:
churn_reason
Budget Cuts            53
Price Too High         51
Company Closed         48
Poor Support           42
No Longer Needed       41
Missing Features       40
Switched Competitor    38
Name: count, dtype: int64

company_size:
company_size
11-50      93
1-10       89
51-200     60
201-500    47
500+       24
Name: count, dtype: int64

In [78]:
for col in data_columns:
    display(churn_by_plan[col].value_counts().to_frame())
    print("-" * 30)

              count
plan
Starter         153
Professional     83
Business         66
Enterprise       11

------------------------------

               count
industry
Real Estate       37
Finance           36
Healthcare        35
Education         34
Consulting        32
Manufacturing     31
Legal             31
Retail            30
Media             24
Technology        23

------------------------------

                     count
acquisition_channel
Referral                76
Organic Search          67
Paid Ads                61
Partner                 58
Social Media            29
Direct Sales            22

------------------------------

               count
region
North America    139
Europe            89
Asia Pacific      48
Latin America     37

------------------------------

                     count
churn_reason
Budget Cuts             53
Price Too High          51
Company Closed          48
Poor Support            42
No Longer Needed        41
Missing Features        40
Switched Competitor     38

------------------------------

              count
company_size
11-50            93
1-10             89
51-200           60
201-500          47
500+             24

------------------------------

In [85]:
for col in data_columns: 
    total = subscriptions.groupby(col).size().rename('total')
    churned = subscriptions[subscriptions['churned']=='Yes'].groupby(col).size().rename('churned_count')
    churn_rate = (churned/total*100).round(2).rename('churn_rate_%')
    
    display(pd.concat([total, churned, churn_rate], axis=1).sort_values('churn_rate_%', ascending=False))
    print("-" * 30)

              total  churned_count  churn_rate_%
plan
Starter         217            153         70.51
Professional    173             83         47.98
Business        160             66         41.25
Enterprise       50             11         22.00

------------------------------

               total  churned_count  churn_rate_%
industry
Real Estate       61             37         60.66
Finance           61             36         59.02
Retail            52             30         57.69
Healthcare        61             35         57.38
Legal             57             31         54.39
Consulting        62             32         51.61
Manufacturing     64             31         48.44
Technology        51             23         45.10
Media             54             24         44.44
Education         77             34         44.16

------------------------------

                     total  churned_count  churn_rate_%
acquisition_channel
Referral               124             76         61.29
Partner                100             58         58.00
Social Media            52             29         55.77
Paid Ads               115             61         53.04
Organic Search         153             67         43.79
Direct Sales            56             22         39.29

------------------------------

               total  churned_count  churn_rate_%
region
Latin America     60             37         61.67
Europe           162             89         54.94
Asia Pacific      94             48         51.06
North America    284            139         48.94

------------------------------

                     total  churned_count  churn_rate_%
churn_reason
Budget Cuts             53             53         100.0
Company Closed          48             48         100.0
Missing Features        40             40         100.0
No Longer Needed        41             41         100.0
Poor Support            42             42         100.0
Price Too High          51             51         100.0
Switched Competitor     38             38         100.0

------------------------------

              total  churned_count  churn_rate_%
company_size
500+             38             24         63.16
1-10            157             89         56.69
201-500          88             47         53.41
11-50           176             93         52.84
51-200          141             60         42.55

------------------------------

In [97]:
ch_rate = subscriptions[subscriptions['churned'] == 'Yes']

In [102]:
overall_churn_rate = ((ch_rate["customer_id"].count()/ subscriptions['customer_id'].count())*100).round(2)

In [103]:
overall_churn_rate

np.float64(52.17)